#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

//    ----------------------------------------------------------------------
//    Copyright © 2024, 2025  Pellegrino Prevete
//
//    All rights reserved
//    ----------------------------------------------------------------------
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.

const
  { spawn } =
    require(
      "node:child_process");
_spawn =
  spawn;
const
  _cert_tools_module =
    require(
      'cert-tools');
_cert_gen =
  _cert_tools_module._cert_gen;
const
  _sha_module =
    require(
      'js-sha256');
_sha256 =
  _sha_module.sha256;
const
  _libcrash =
  require(
    'crash-js');
_error_display =
  _libcrash._error_display;
_ext_rm =
  _libcrash._ext_rm;
_file_exists =
  _libcrash._file_exists;
_file_read =
  _libcrash._file_read;
_file_write =
  _libcrash._file_write;
_fs_worker_start =
  _libcrash._fs_worker_start;
_json_read =
  _libcrash._json_read;
_ls =
  _libcrash._ls;
_mkdir =
  _libcrash._mkdir;
_msg_info =
  _libcrash._msg_info;
_msg_error =
  _libcrash._msg_error;

function
  _path_encode(
    _path) {
  let
    _string;
  _string =
    _sha256(
      _path + "\n");
  return _string;
}

function
  _serve(
    _target_directory,
    _listen_uris,
    _target_port,
    _index_redirect,
    _debug_enabled,
    _config_file,
    _logging_disabled,
    _cors_enabled,
    _clipboard_disable,
    _compression_disable,
    _no_etags,
    _symlinks_enabled,
    _ssl_cert,
    _ssl_key,
    _ssl_pass,
    _port_switching_disabled) {
  let
    _cmd,
    _cmd_args,
    _serve_process,
    _uri;
  for ( _uri of _listen_uris ) {
    _cmd_args.push(
      "-l",
      _uri);
  }
  _cmd_args.push(
    "--port",
    _target_port);
  if ( _index_redirect == "y" ) {
    _cmd_args.push(
      "--single");
  }
  if ( _debug_enabled != "n" ) {
    _cmd_args.push(
      "--debug");
  }
  if ( _config_file != "" ) {
    _cmd_args.push(
      "--config",
      _config_file);
  }
  if ( _logging_disabled == "y" ) {
    _cmd_args.push(
      "--no-request-logging");
  }
  if ( _cors_enabled == "y" ) {
    _cmd_args.push(
      "--cors");
  }
  if ( _clipboard_disabled == "y" ) {
    _cmd_args.push(
      "--no-clipboard");
  }
  if ( _compression_disabled == "y" ) {
    _cmd_args.push(
      "--no-compression");
  }
  if ( _etag_disabled == "y" ) {
    _cmd_args.push(
      "--no-etag");
  }
  if ( _symlinks_enabled == "y" ) {
    _cmd_args.push(
      "--symlinks");
  }
  if ( _port_switching_disabled == "y" ) {
    _cmd_args.push(
      "--no-port-switching");
  }
  if ( _ssl_cert != "" ) {
    _cmd_args.push(
      "--ssl-cert",
      ssl_cert);
  }
  if ( _ssl_key != "" ) {
    _cmd_args.push(
      "--ssl-key",
      ssl_key);
  }
  if ( _ssl_pass != "" ) {
    _cmd_args.push(
      "--ssl-pass",
      ssl_pass);
  }
  _serve_process =
    _spawn(
      _cmd,
      _cmd_opts);
  _serve_process.stdout.on(
    'data',
    (data) => {
      console.log(
        `${data}`);
    });
}

async function
  _safely_serve(
    _target_directory,
    _listen_uris,
    _target_port,
    _index_redirect,
    _debug_enabled,
    _config_file,
    _logging_disabled,
    _cors_enabled,
    _clipboard_disable,
    _compression_disable,
    _no_etags,
    _symlinks_enabled,
    _cert_new,
    _ssl_cert,
    _ssl_key,
    _ssl_pass,
    _port_switching_disabled,
    _keys_length,
    _serial_number,
    _validity_min,
    _validity_max,
    _domain_name,
    _country_name,
    _state_name,
    _locality_name,
    _organization_name,
    _organization_unit) {
  let
    _alt_names,
    _attrs,
    _basic_constraints,
    _cert,
    _ext_key_usage,
    _key_usage,
    _key_pem,
    _key_private,
    _keys,
    _keys_pem,
    _ns_cert_type,
    _pem,
    _serve,
    _subject_alt_name,
    _subject_key_identifier;
  if ( ! _file_exists(
           _ssl_cert) &&
       _cert_new == "y" ) {
    _cert_gen(
    );
  }
  // _serve =
  //   import(
  //     'serve');
  // if ( _ssl_cert != "" &&
  //      ( ! _file_exists(
  //        _ssl_cert) ) ) {
  //   
  // }
  _keys_length =
    Number(
      _keys_length);
  if ( _key_private_path == "" ||
       ! _file_exists(
           _key_private_path) ) {
    _keys =
      _rsa.generateKeyPair(
        _keys_length);
    _key_pem =
      _pki.privateKeyToPem(
        _keys.privateKey);
    _file_write(
      _key_private_path,
      _key_pem);
    _key_private =
      _keys.privateKey;
  }
  else {
    _key_pem =
      _file_read(
        _key_private_path);
    _key_private =
      _pki.privateKeyFromPem(
        _key_pem);
    _keys =
      { privateKey:
          _key_private };
  }
  if ( _log_file != "" ) {
    if ( typeof window !== 'undefined') {
      await _fs_worker_start(
          "fs-worker.js");
    }
    _file_write(
      _log_file,
      _whatever_log);
  }
  return true;
}

module.exports = {
  _path_encode:
    _path_encode,
  _safely_serve:
    _safely_serve
};
