#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

//    ----------------------------------------------------------------------
//    Copyright © 2024, 2025  Pellegrino Prevete
//
//    All rights reserved
//    ----------------------------------------------------------------------
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.

const
  _serve_module =
    require(
      'serve');
const
  _cert_tools_module =
    require(
      'cert-tools');
const
  _libcrash =
  require(
    'crash-js');
_error_display =
  _libcrash._error_display;
_ext_rm =
  _libcrash._ext_rm;
_file_exists =
  _libcrash._file_exists;
_file_read =
  _libcrash._file_read;
_file_write =
  _libcrash._file_write;
_fs_worker_start =
  _libcrash._fs_worker_start;
_json_read =
  _libcrash._json_read;
_ls =
  _libcrash._ls;
_mkdir =
  _libcrash._mkdir;
_msg_info =
  _libcrash._msg_info;
_msg_error =
  _libcrash._msg_error;

function
  _safely_serve(
    _key_private_path,
    _keys_length,
    _serial_number,
    _validity_min,
    _validity_max,
    _domain_name,
    _country_name,
    _state_name,
    _locality_name,
    _organization_name,
    _organization_unit,
    _output_file) {
  let
    _alt_names,
    _attrs,
    _basic_constraints,
    _cert,
    _ext_key_usage,
    _key_usage,
    _key_pem,
    _key_private,
    _keys,
    _keys_pem,
    _ns_cert_type,
    _pem,
    _subject_alt_name,
    _subject_key_identifier;
  _keys_length =
    Number(
      _keys_length);
  if ( _key_private_path == "" ||
       ! _file_exists(
           _key_private_path) ) {
    _keys =
      _rsa.generateKeyPair(
        _keys_length);
    _key_pem =
      _pki.privateKeyToPem(
        _keys.privateKey);
    _file_write(
      _key_private_path,
      _key_pem);
    _key_private =
      _keys.privateKey;
  }
  else {
    _key_pem =
      _file_read(
        _key_private_path);
    _key_private =
      _pki.privateKeyFromPem(
        _key_pem);
    _keys =
      { privateKey:
          _key_private };
  }
  if ( _log_file != "" ) {
    if ( typeof window !== 'undefined') {
      await _fs_worker_start(
          "fs-worker.js");
    }
    _file_write(
      _log_file,
      _whatever_log);
  }
  return true;
}

module.exports = {
  _safely_serve:
    _safely_serve
};
